[project]
name = "pendulum-nn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anywidget>=0.9.21",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "nbformat>=5.10.4",
    "networkx>=3.6.1",
    "numpy>=2.4.2",
    "plotly>=6.6.0",
    "plotly-stubs>=0.1.2",
]
